# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: ros:melodic
    steps:
      - checkout
      - run:
        name: setup
        command: ./setup.bash

      - run:
        name: build
        command: source /opt/ros/melodic/setup.bash && catkin build

      - run:
        name: test
        command: source /opt/ros/melodic/setup.bash && catkin run_tests && catkin_test_results

workflows:
  main:
    jobs:
      - build_and_test
